name: mi_card_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-125.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttericon: ^2.0.0
  flutter_web_browser: ^0.17.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/profile.jpg
    - assets/images/github.png
  
  fonts:
  - family: Pacifico
    fonts:
    - asset: assets/fonts/Pacifico-Regular.ttf
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway-Black.ttf
      - asset: assets/fonts/Raleway-BoldItalic.ttf
        style: italic
      - asset: assets/fonts/Raleway-Light.ttf
      - asset: assets/fonts/Raleway-Medium.ttf

  - family: CrimsonText
    fonts:
      - asset: assets/fonts/CrimsonText-Regular.ttf

  - family: Play
    fonts:
      - asset: assets/fonts/Play-Regular.ttf

  - family:  MyFlutterApp
    fonts:
      - asset: assets/fonts/MyFlutterApp.ttf